function fileHandler_html4(d,g){if("upload"==KUPLOADTOP.G_CURRKUPLOADER._config.mode){var f=[],a=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileCount,b=!0,c=[],k={file:d,name:getFileName(g,!1),size:"",type:"",lastModifiedDate:""};c.push(k);var h;try{if(k={fileList:c,dropZoneId:""},"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.initAddAllFile?h=KUPLOADTOP.G_CURRKUPLOADER._config.event.initAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID,k):"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_InitAddAllFile&&
(h=KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_InitAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID,k)),void 0!==h){if(null===h)return;if(0<h.length)files=h;else if(!h)return}}catch(e){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(e)}h=[];var n=KUPLOADTOP.G_CURRKUPLOADER.frameWin.getTotalFileCount(),m=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.duplication,q=0,p=!1;if(p=reservedWordCheck(c[0].name))alert(RAONKUpload_Lang.message_reservedWord_file);else{p=!1;"0"==KUPLOADTOP.G_CURRKUPLOADER._config.allowDuplicationFile&&
(p=sameFileCheck(c[0]));if(p)"0"==m&&alert(c[0].name+" "+RAONKUpload_Lang.message_duplication_file);else{var m=!1,p=KUPLOADTOP.G_CURRKUPLOADER._config.extension,u=p.extArr.length;if(0<u){var w=p.allowOrLimit;if("1"==w){for(var v=getExtension(c[0].name),r=0;r<u;r++)if(("***"==p.extArr[r]?"":p.extArr[r])==v){m=!0;break}m||h.push(""==v?'" "':v)}else for(v=getExtension(c[0].name),r=0;r<u;r++)if(("***"==p.extArr[r]?"":p.extArr[r])==v){m=!1;h.push(""==v?'" "':v);break}else m=!0}else m=!0;calcTotalSize();
p=TOTALREALFILENUM;if(0!=a&&p+1>a){b=RAONKUpload_Lang.message_limit_num;b=b.replace("{0}",a);alert(b);return}if(m){var x=a="";document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID)&&(x=document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value);null==g&&(g="");(a=g)&&(a=KUPLOADTOP.RAONKUPLOAD.util.trim(a));if("undefined"==typeof a||null==a)a="undefined"==typeof filePathSplit[0]||null==filePathSplit[0]?"":filePathSplit[0].substring(0,filePathSplit[0].lastIndexOf(KUPLOADTOP.RAONKUPLOAD.UserAgent.osSeparator)+
1)+c[0].name;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAddEvent)try{var l=c[0].file,k={strName:c[0].name,nSize:c[0].size,nIndex:n+q,strPath:a,dropZoneId:"",objFile:l,isFolder:"1"==c[0].isFolder?!0:!1,strPreviewUrl:""};"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.beforeAddFile?b=KUPLOADTOP.G_CURRKUPLOADER._config.event.beforeAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,k):"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_BeforeAddFile&&(b=KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_BeforeAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,
k));!1!==b&&(b=!0)}catch(y){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(y)}if(b){b=c[0].type;if(null==b||void 0==b||""==b)b="application/octet-stream";a={file:c[0].file,guid:"",fileIdx:"",webPath:"",originName:c[0].name,fileSize:c[0].size,uploadName:"",uploadPath:"",logicalPath:"",status:"ready",fileExt:"",isDelete:"n",isWebFile:"n",localPath:a,customValue:"",responseCustomValue:"",headerEx:"",lastModifiedDate:c[0].lastModifiedDate,mimeType:b};RESULTFILELIST.push(a);a.isFolder="0";addFileList(a);
if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEvent)try{calcTotalSize(),l=c[0].file,k={strName:c[0].name,nSize:c[0].size,nIndex:n+q,strPath:a.localPath,dropZoneId:"",objFile:l,isFolder:"1"==c[0].isFolder?!0:!1,strPreviewUrl:""},f.push(k),"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddFile?KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,k):"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddFile&&KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddFile(KUPLOADTOP.G_CURRKUPLOADER.ID,
k)}catch(z){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(z)}q++;c=document.getElementById("files_container");KUPLOADTOP.G_CURRKUPLOADER.TagID=KUPLOADTOP.RAONKUPLOAD.util.makeGuidTagName();l=document.createElement("form");l.setAttribute("id","form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);l.setAttribute("method","post");l.setAttribute("enctype","multipart/form-data");l.setAttribute("encoding","multipart/form-data");a=document.createElement("span");a.className="input_image_add";a.innerHTML=RAONKUpload_Lang.btn_add;
""!=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor&&(a.style.background=KUPLOADTOP.G_CURRKUPLOADER._config.customHeaderColor);""!=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor&&(a.style.color=KUPLOADTOP.G_CURRKUPLOADER._config.customFooterColor);var t=document.createElement("input");t.setAttribute("id","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);t.setAttribute("name","file_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);t.setAttribute("type","file");KUPLOADTOP.RAONKUPLOAD.util.addEvent(t,"change",
function(){fileHandler_html4(t,t.value)});KUPLOADTOP.RAONKUPLOAD.util.addEvent(t,"blur",function(){focusHandler(t)});b=document.createElement("input");b.setAttribute("id","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);b.setAttribute("name","tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID);b.setAttribute("type","hidden");b.setAttribute("value","0");l.appendChild(a);l.appendChild(t);l.appendChild(b);a=document.createElement("div");a.appendChild(l);c.appendChild(a);a.previousSibling&&(a.previousSibling.style.display=
"none",a.previousSibling.childNodes[0].childNodes[1].tabIndex="-1")}}}displayTotalSizeAndNum();c=h.length;if(0<c){b="";l=KUPLOADTOP.G_CURRKUPLOADER._config.extension.extArr;a=l.length;for(b=0;b<a;b++)"***"==l[b]&&(l[b]='" "');"1"==w?1<c?(b=RAONKUpload_Lang.message_not_allow_exts,b=b.replace("{0}",c),b=b.replace("{1}",l)):(b=RAONKUpload_Lang.message_not_allow_ext,b=b.replace("{0}",l),b=b.replace("{1}",h[0])):1<c?(b=RAONKUpload_Lang.message_not_limit_exts,b=b.replace("{0}",c),b=b.replace("{1}",l)):
(b=RAONKUpload_Lang.message_not_limit_ext,b=b.replace("{0}",l),b=b.replace("{1}",h[0]));alert(b)}"1"==KUPLOADTOP.G_CURRKUPLOADER._config.use_file_sort&&"1"==KUPLOADTOP.G_CURRKUPLOADER._config.auto_sort&&"1"!=KUPLOADTOP.G_CURRKUPLOADER._config.sort_field&&sortTotalFileList(KUPLOADTOP.G_CURRKUPLOADER._config.sort_field,KUPLOADTOP.G_CURRKUPLOADER._config.sort_ascdesc);calcTotalSize();fileListSortIconReset();setFileListBorder();setListvalue();setLargeFileAllList();1==x&&(document.getElementById("file_"+
KUPLOADTOP.G_CURRKUPLOADER.TagID).focus(),document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundImage="url("+KUPLOADTOP.G_CURRKUPLOADER._config.webPath.image+"img_bt_line.png)",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundRepeat="no-repeat",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionY="2px",document.getElementById("form_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).childNodes[0].style.backgroundPositionX=
"1px",document.getElementById("tab_"+KUPLOADTOP.G_CURRKUPLOADER.TagID).value="1",G_FileHandlerControl=0);"thumbs"==KUPLOADTOP.G_CURRKUPLOADER._config.views&&thumbsViewWithCanvas();if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useAfterAddEndTimeEvent&&0<q)try{k={arrFileList:f},"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddAllFile?KUPLOADTOP.G_CURRKUPLOADER._config.event.afterAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID,k):"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddAllFile&&
KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_AfterAddAllFile(KUPLOADTOP.G_CURRKUPLOADER.ID,k)}catch(A){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(A)}}}}
function processUploadHtml4(){if(!KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){var d=getDialogDocument();0==upload_complete_count&&(G_UploadStartTime=(new Date).getTime()/1E3);var g=document.getElementById("files_container").getElementsByTagName("form"),f=0;if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.skipSentFile)for(var a=0;a<uploaders[upload_complete_count];a++)RESULTFILELIST[a].file&&"complete"==RESULTFILELIST[a].status&&f++;g=g[upload_complete_count+f];f=document.charset;document.charset="utf-8";
var b=upload_complete_count.toString();b==(uploaders.length-1).toString()&&(b+="z");RESULTFILELIST[uploaders[upload_complete_count]].guid=KUPLOADTOP.RAONKUPLOAD.util.makeGuid();var c=g.getElementsByTagName("input"),k=c[0],c=c[1];g.removeChild(c);for(var h=0,e=RESULTFILELIST.length,a=0;a<uploaders[upload_complete_count];a++)"n"==RESULTFILELIST[a].isDelete&&(h+=parseInt(RESULTFILELIST[a].fileSize,10));for(a=uploaders[upload_complete_count]+1;a<e;a++)"y"==RESULTFILELIST[a].isWebFile&&(h+=parseInt(RESULTFILELIST[a].fileSize,
10));e=""+("kc"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"c02"+KUPLOADTOP.RAONKSolution.Agent.vertical);e+="k01"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k12"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].guid+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k14"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].originName+
KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k15"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k16"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.fileNameRuleEx+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k17"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.folderNameRule+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k20"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
b+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k21"+KUPLOADTOP.RAONKSolution.Agent.formfeed+RESULTFILELIST[uploaders[upload_complete_count]].customValue+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k22"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k23"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical;e+="k24"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.allowedZeroFileSize+KUPLOADTOP.RAONKSolution.Agent.vertical;
"1"==KUPLOADTOP.G_CURRKUPLOADER._config.security.fileExtensionDetector&&(e+="k29"+KUPLOADTOP.RAONKSolution.Agent.formfeed+"1"+KUPLOADTOP.RAONKSolution.Agent.vertical);a=KUPLOADTOP.G_CURRKUPLOADER._config.maxOneFileSize;0!=a&&(e+="k40"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical);a=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileSize;0!=a&&(e+="k41"+KUPLOADTOP.RAONKSolution.Agent.formfeed+a+KUPLOADTOP.RAONKSolution.Agent.vertical,e+="k42"+KUPLOADTOP.RAONKSolution.Agent.formfeed+
h+KUPLOADTOP.RAONKSolution.Agent.vertical);KUPLOADTOP.G_CURRKUPLOADER._config.cloudInfo.Use&&"2"==KUPLOADTOP.G_CURRKUPLOADER._config.cloudInfo.Use&&(e+="k46"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.G_CURRKUPLOADER._config.cloudInfo.Use+KUPLOADTOP.RAONKSolution.Agent.vertical);a=KUPLOADTOP.G_CURRKUPLOADER._config.security.requestValidationSecond;"0"!=a&&(h=new Date,h.setSeconds(h.getSeconds()+parseInt(a,10)),e+="krv"+KUPLOADTOP.RAONKSolution.Agent.formfeed+KUPLOADTOP.RAONKUPLOAD.util.getDateFormat(new Date(h.getTime()+
6E4*h.getTimezoneOffset()),"yyyyMMddHHmmss")+KUPLOADTOP.RAONKSolution.Agent.vertical);a=document.createElement("input");a.type="hidden";e=KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(e);a.name=e.name;a.value=e.value;g.insertBefore(a,k);KUPLOADTOP.RAONKUPLOAD.util.setCSRFHiddenInput(g,KUPLOADTOP.G_CURRKUPLOADER._config.addCSRFToken,document);h=G_FormData.length;e=[];for(b=0;b<h;b++){var n=G_FormData[b].form_value,n="1"<=KUPLOADTOP.G_CURRKUPLOADER._config.security.encryptParam?KUPLOADTOP.RAONKUPLOAD.util.makeEncryptParamFinal(n,
!0).value:encodeURIComponent(n),m=document.createElement("input");m.type="hidden";m.name=G_FormData[b].form_name;m.value=n;g.insertBefore(m,k);e.push(m)}var q=document.createElement("div"),b=KUPLOADTOP.RAONKUPLOAD.util.getDefaultIframeSrc();q.innerHTML='<iframe name="uploadframe" id="uploadframe" style="display:none;" src="'+b+'"></iframe>';q.style.display="none";document.body.appendChild(q);var p=KUPLOADTOP.RAONKUPLOAD.util.getPostMessageTargetOrigin(w,KUPLOADTOP.G_CURRKUPLOADER._config);KUPLOADTOP.RAONKUPLOAD.util.addEvent(q.firstChild,
"load",function(){q.firstChild.contentWindow.postMessage("check",p);if(0==KUPLOADTOP.G_CURRKUPLOADER._config.isCrossDomain){KUPLOADTOP.RAONKUPLOAD.util.removeEvent(window,"message",u);var a=q.firstChild.contentWindow.document.body.innerHTML,a=KUPLOADTOP.RAONKUPLOAD.util.trim(a);document.body.removeChild(q);uploadEnd_html4(a)}},!0);if(window.postMessage){var u=function(a){KUPLOADTOP.RAONKUPLOAD.util.removeEvent(window,"message",u);document.body.removeChild(q);0==w.indexOf(a.origin)&&(a=KUPLOADTOP.RAONKUPLOAD.util.trim(a.data),
uploadEnd_html4(a))};KUPLOADTOP.RAONKUPLOAD.util.addEvent(window,"message",u)}g.setAttribute("target","uploadframe");var w=KUPLOADTOP.G_CURRKUPLOADER._config.handlerUrl;g.setAttribute("action",w);d.getElementById("RAON_K_UP_current_upload_file_name").innerHTML=" "+RESULTFILELIST[uploaders[upload_complete_count]].originName;g.submit();document.charset=f;g.removeChild(a);for(a=h-1;0<=a;a--)g.removeChild(e[a]);g.insertBefore(c,k.nextSibling);uploadProgress_html4(upload_complete_count,TOTALUPLOADNUM,
50)}}
function uploadEnd_html4(d){var g=getDialogDocument(),f=function(a,b){try{var c={strType:"upload",strStatus:"error",strTransferId:G_TransferId};"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.transferStatusChange?KUPLOADTOP.G_CURRKUPLOADER._config.event.transferStatusChange(KUPLOADTOP.G_CURRKUPLOADER.ID,c):"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_TransferStatusChange&&KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_TransferStatusChange(KUPLOADTOP.G_CURRKUPLOADER.ID,c)}catch(d){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(d)}c=
getUploadedFileListObj();try{if(c={strType:"upload",strCode:a,strMessage:b,arrUploadedFileList:c},"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.onError)KUPLOADTOP.G_CURRKUPLOADER._config.event.onError(KUPLOADTOP.G_CURRKUPLOADER.ID,c);else"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError?KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_OnError(KUPLOADTOP.G_CURRKUPLOADER.ID,c):alert("Error Code : "+c.strCode+"\nError Message : "+c.strMessage)}catch(e){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(e)}G_TransferId=
"";if(1==G_MultiTranferCheck)G_MultiTranferCheck=4;else try{fileListReset()}catch(k){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(k)}clearInterval(G_IntervalObj);PREVIOUSUPLOADEDSIZE=0;g.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=
!1);displayCommonReady(!1,KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()};d=KUPLOADTOP.RAONKUPLOAD.util.parseDataFromServer(d);if(0==d.indexOf("[OK]"))if(d=d.replace("[OK]",""),d=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(d),"C012|response data decrypt error"==d)d=d.split("|"),f(d[0],d[1]);else{f=d.split(KUPLOADTOP.RAONKSolution.Agent.formfeed);d=f[0];var a="",b="",c=d.indexOf("::");-1<c&&(a=d.substring(0,c),d=d.substring(c+2,d.length));c=d.indexOf(":");
-1<c&&(b=d.substring(0,c),d=d.substring(c+1,d.length));c="";c=d.length;"|"==d.substring(c-1,c)?(d=d.substring(0,c-1),c=getFileName(d,!1),d=d.substring(0,d.lastIndexOf("/"+c))):c=getFileName(d,!1);RESULTFILELIST[uploaders[upload_complete_count]].uploadName=c;RESULTFILELIST[uploaders[upload_complete_count]].uploadPath=d;RESULTFILELIST[uploaders[upload_complete_count]].fileSize=f[2];RESULTFILELIST[uploaders[upload_complete_count]].status="complete";RESULTFILELIST[uploaders[upload_complete_count]].logicalPath=
"";RESULTFILELIST[uploaders[upload_complete_count]].responseCustomValue=f[1];""!=b&&(RESULTFILELIST[uploaders[upload_complete_count]].originName=b);RESULTFILELIST[uploaders[upload_complete_count]].hashValue=a;KUPLOADTOP.G_CURRKUPLOADER.uploadedTaskId="";KUPLOADTOP.G_CURRKUPLOADER.uploadedSize=0;PREVIOUSUPLOADEDSIZE+=parseInt(f[2],10);clearInterval(G_IntervalObj);uploadProgressComplete_html4(KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(f[2]));upload_complete_count++;if(KUPLOADTOP.G_CURRKUPLOADER._config.uploadCancel){try{f=
{strType:"upload",strStatus:"cancel",strTransferId:G_TransferId},"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.transferStatusChange?KUPLOADTOP.G_CURRKUPLOADER._config.event.transferStatusChange(KUPLOADTOP.G_CURRKUPLOADER.ID,f):"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_TransferStatusChange&&KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_TransferStatusChange(KUPLOADTOP.G_CURRKUPLOADER.ID,f)}catch(k){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(k)}if("1"==KUPLOADTOP.G_CURRKUPLOADER._config.useUploadingCancelEvent){f=
{strType:"upload",bAutoTransferFlag:!1,arrAllFileList:null,arrUploadedFileList:getUploadedFileListObj()};try{"function"===typeof KUPLOADTOP.G_CURRKUPLOADER._config.event.uploadingCancel?KUPLOADTOP.G_CURRKUPLOADER._config.event.uploadingCancel(KUPLOADTOP.G_CURRKUPLOADER.ID,f):"function"===typeof KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_UploadingCancel&&KUPLOADTOP.KUPLOADWIN.RAONKUPLOAD_UploadingCancel(KUPLOADTOP.G_CURRKUPLOADER.ID,f)}catch(h){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(h)}}G_TransferId="";
if(1==G_MultiTranferCheck)G_MultiTranferCheck=3;else try{fileListReset()}catch(e){KUPLOADTOP.RAONKUPLOAD.logMode&&console.log(e)}PREVIOUSUPLOADEDSIZE=0;g.getElementById("RAON_K_UP_upload_size").innerHTML="-";clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval);KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=null;KUPLOADTOP.G_CURRKUPLOADER.processTime=0;0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1);displayCommonReady(!1,
KUPLOADTOP.G_CURRKUPLOADER);closeSendDialog();KUPLOADTOP.G_CURRKUPLOADER.cancel()}else upload_complete_count==TOTALUPLOADNUM?(PREVIOUSUPLOADEDSIZE=0,g.getElementById("RAON_K_UP_upload_size").innerHTML="-",totalUploadComplete(),0<getSessionKeepData(KUPLOADTOP.G_CURRKUPLOADER).length&&(KUPLOADTOP.G_CURRKUPLOADER._config.sessionKeep.requestFlag=!1)):(f=uploaders.indexOf(uploaders[upload_complete_count]),adjustUploadFileListScroll(f,upload_complete_count,TOTALUPLOADNUM),processUploadHtml4())}else{0==
d.indexOf("[FAIL]")?(d=d.replace("[FAIL]",""),d=KUPLOADTOP.RAONKUPLOAD.util.makeDecryptReponseMessage(d),d=KUPLOADTOP.RAONKUPLOAD.util.getCodeAndMessage(d)):d={code:"C016",message:RAONKUpload_Lang.error_info.error_code_C016?RAONKUpload_Lang.error_info.error_code_C016:"There is a problem with the server response.",responseText:d};b=KUPLOADTOP.G_CURRKUPLOADER._config.maxOneFileSize;c=KUPLOADTOP.G_CURRKUPLOADER._config.maxTotalFileSize;a="";"020"==d.code?(a=RAONKUpload_Lang.message_limit_one_size,a=
a.replace("{0}",KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(b).toString)):a="021"==d.code?RAONKUpload_Lang.message_file_ext_detect_html4:"022"==d.code?RAONKUpload_Lang.file_maximum+" "+KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(c).toString+RAONKUpload_Lang.message_limit_size:d.message;b=0;if("020"==d.code||"021"==d.code||"022"==d.code){for(c=0;c<uploaders[upload_complete_count];c++)"y"==RESULTFILELIST[c].isDelete&&b++;var n=uploaders[upload_complete_count]-b;setSelectFile(n,0);n=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm;
KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=1;KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID);KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=n}if("022"==d.code)for(var m=RESULTFILELIST.length,c=uploaders[upload_complete_count];c<m;c++)"y"==RESULTFILELIST[c].isDelete?b++:"n"==RESULTFILELIST[c].isWebFile&&(n=c-b,setSelectFile(n,0),n=KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm,KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=
1,KUPLOADTOP.RAONKUPLOAD.DeleteSelectedFile(KUPLOADTOP.G_CURRKUPLOADER.ID),KUPLOADTOP.G_CURRKUPLOADER._config.disableAlertMessage.disableDeleteConfirm=n,c--,m--);f(d.code,a)}}
function uploadProgress_html4(d,g,f){var a=getDialogDocument();adjustUploadFileListScroll(d-1,d,g);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[d]).style.width="0%";G_IntervalObj=setInterval(function(){b()},400);var b=function(){var b;b=0;if(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[d])){b=a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[d]).style.width.split("%");b=Math.round(1*b[0]*f/100);b++;if(b==parseInt(3*f/5,10)+1)c("1");else if(b==parseInt(4*f/5,10)+
1)c("2");else if(b==parseInt(9*f/10,10)+1)c("3");else if(b==parseInt(24*f/25,10)+1){c("4");return}if(1==b)if(a.getElementById("RAON_K_UP_upload_count"))a.getElementById("RAON_K_UP_upload_count").innerHTML=d+1+"/"+g;else return;var h=parseInt(1/f*100*b,10);a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[d])&&(a.getElementById("RAON_K_UP_uploadFileProgress_"+uploaders[d]).style.width=h+"%",a.getElementById("RAON_K_UP_current_upload_progress_bar")&&(a.getElementById("RAON_K_UP_current_upload_progress_bar").style.width=
h+"%"),b=parseInt(1*d/g*100,10)+parseInt(parseInt(1/f*100*b,10)/g,10),a.getElementById("RAON_K_UP_total_upload_percent")&&(a.getElementById("RAON_K_UP_total_upload_percent").innerHTML=b+"%",a.getElementById("RAON_K_UP_total_upload_progress_bar")&&(a.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=b+"%",a.getElementById("RAON_K_UP_upload_size")&&0==PREVIOUSUPLOADEDSIZE&&(a.getElementById("RAON_K_UP_upload_size").innerHTML="-"))))}},c=function(a){"1"==a?(clearInterval(G_IntervalObj),
G_IntervalObj=setInterval(function(){b()},800)):"2"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){b()},1E3)):"3"==a?(clearInterval(G_IntervalObj),G_IntervalObj=setInterval(function(){b()},1200)):"4"==a&&clearInterval(G_IntervalObj)};null==KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval&&(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=setInterval(function(){a.getElementById("RAON_K_UP_process_time").innerHTML=viewTime(++KUPLOADTOP.G_CURRKUPLOADER.processTime)},1E3))}
function uploadProgressComplete_html4(d){var g=getDialogDocument(),f=uploaders[upload_complete_count];if(void 0!=f){var a=parseInt(1*(upload_complete_count+1)/TOTALUPLOADNUM*100,10);g.getElementById("RAON_K_UP_current_upload_progress_bar").style.width="100%";g.getElementById("RAON_K_UP_uploadFileProgress_"+f).style.width="100%";g.getElementById("RAON_K_UP_uploadFilePercent_"+f).style.color="";g.getElementById("RAON_K_UP_uploadFilePercent_"+f).innerHTML="100%";g.getElementById("RAON_K_UP_uploadFileSize_"+
f).innerHTML=d.toString;UPLOADIDX++;g.getElementById("RAON_K_UP_upload_count").innerHTML=upload_complete_count+1+"/"+TOTALUPLOADNUM;g.getElementById("RAON_K_UP_total_upload_percent").innerHTML=a+"%";g.getElementById("RAON_K_UP_total_upload_progress_bar").style.width=a+"%";g.getElementById("RAON_K_UP_upload_size").innerHTML=KUPLOADTOP.RAONKUPLOAD.util.bytesToSize(PREVIOUSUPLOADEDSIZE).toString;100==a&&(clearInterval(KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval),KUPLOADTOP.G_CURRKUPLOADER.processTimeInterval=
null,KUPLOADTOP.G_CURRKUPLOADER.processTime=0)}};
