(function(){function k(a){var c={};a=a.split(",");for(var d=0;d<a.length;d++)c[a[d]]=!0;return c}var r=50,t=/^<([-A-Za-z0-9_]+)((?:\s+\w+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,w=/^<\/([-A-Za-z0-9_:@.]+)[^>]*>/,y=/([-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,u=/^<([-A-Za-z0-9_:-]+)((?:\s+[a-zA-Z_0-9:-]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,z=/([-A-Za-z0-9_:-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
A=k("colgroup,col"),B=k("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed");k("area,base,basefont,br,col,frame,img,input,isindex,link,meta,param,embed");var C=k("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul,h1,h2,h3,h4,h5,h6,figure,nav,section,article"),x=!1,n="a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var",
q=k(n),D=k("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),E=k("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),F=k("");"undefined"==typeof RAONK_EDITOR&&(RAONK_EDITOR={});RAONK_EDITOR.HTMLParser=function(a,c,d){function g(a,b,f,c){b=b.toLowerCase();if(C[b]){for("table"!=h.last()&&"tbody"!=h.last()||"td"!=b||g("","tr","","");h.last()&&q[h.last()];)e("",h.last());"p"!=h.last()||"table"!=b&&"hr"!=b&&"center"!=b&&"figure"!=b||e("","p")}D[b]&&
h.last()==b&&e("",b);(c=B[b]||!!c)||h.push(b);if(d.start){var l=[];a=t.test(a)?y:z;f.replace(a,function(a,b,d,f,c){d=d?d:f?f:c?c:E[b]?b:"";f="";""!=a&&(a=a.substring(a.indexOf(b)+b.length),a=a.substring(a.indexOf("=")+1),a=a.replace(/^\s+/,""),f=a.substring(0,1),"'"!=f&&'"'!=f&&(f=""));l.push({name:b,value:d,escaped:d.replace(/(^|[^\\])"/g,'$1\\"'),quotationmark:f})});d.start&&d.start(b,l,c)}}function e(a,b){if(b)for(b=b.toLowerCase(),f=h.length-1;0<=f&&h[f]!=b;f--);else var f=0;if(0<=f){for(var c=
h.length-1;c>=f;c--)d.end&&d.end(h[c]);h.length=f}}var b,f,h=[],n=a;for(h.last=function(){return this[this.length-1]};a;){f=!0;if(h.last()&&F[h.last()])a=a.replace(new RegExp("(.*)</"+h.last()+"[^>]*>"),function(a,b){b=b.replace(/\x3c!--(.*?)--\x3e/g,"$1").replace(/<!\[CDATA\[(.*?)]]\x3e/g,"$1");d.chars&&d.chars(b);return""}),e("",h.last());else{var l=a.indexOf("<");b=a.indexOf(">")+1;var m=a.substring(l,b);if(0==a.indexOf("\x3c!--"))b=a.indexOf("--\x3e"),0<=b&&(d.comment&&d.comment(a.substring(4,
b)),a=a.substring(b+3),f=!1);else if(0==a.toLowerCase().indexOf("<?xml"))b=a.indexOf("/>"),0<=b&&(a=a.substring(b+2),f=!1);else if(0!=a.indexOf("<")&&"</"+h.last()+">"==m.replace(/ /ig,""))f=a.substring(0,l),a=a.substring(b),a=f+"</"+h.last()+">"+a,f=!0;else if(0==a.indexOf("</")){if(b=a.match(w))a=a.substring(b[0].length),b[0].replace(w,e),f=!1}else if(0==a.indexOf("<"))if(b=a.match(t))a=a.substring(b[0].length),b[0].replace(t,g),f=!1;else if(b=a.match(u))a=a.substring(b[0].length),b[0].replace(u,
g),f=!1;else{if("1"==KEDITORTOP.G_CURRKEDITOR._config.removeIncorrectAttribute&&(b=a.indexOf("<"),m=a.indexOf(">"),0==b&&0<m)){var p=a.substring(0,m+1),k=l=b=0;0<p.indexOf('\ub9d1\uc740=""')?(b=p.indexOf('\ub9d1\uc740=""'),l=5,k=p.split('\ub9d1\uc740=""').length):0<p.indexOf("\ub9d1\uc740=''")&&(b=p.indexOf("\ub9d1\uc740=''"),l=5,k=p.split("\ub9d1\uc740=''").length);if(2==k&&0<b&&(m=a.substring(m+1),k=p.substring(0,b).lastIndexOf(" "),k<b+l))if(a=p.substring(k,b+l),p=p.replace(a,""),a=p+m,b=a.match(t))a=
a.substring(b[0].length),b[0].replace(t,g),f=!1;else if(b=a.match(u))a=a.substring(b[0].length),b[0].replace(u,g),f=!1}l=/^<([-a-zA-Z._]*@[-a-zA-Z._]*)()>/;if(b=a.match(l))a=a.substring(b[0].length),b[0].replace(l,g),f=!1}f&&(b=a.indexOf("<"),f=0>b?a:a.substring(0,b),a=0>b?"":a.substring(b),d.chars&&(h.last()&&q[h.last()]&&"textarea"!=h.last()&&"script"!=h.last()&&0>h.indexOf("pre")&&0>h.indexOf("xmp")&&(b=!1,l=RegExp("\\S\\n","g"),l.test(f)&&(b=!0),l=RegExp("\\n\\S","g"),l.test(f)&&(b=!0),l=RegExp("\\S\\n\\S",
"g"),l.test(f)&&(b=!0),b?f=f.replace(/\n/g," "):(l=RegExp("\\n\\n","g"),l.test(f)&&""==f.trim()?f=f.replace(/\n\n/g,""):f==unescape("%20%20")&&(b=new RegExp(unescape("%20"),"g"),f=f.replace(b,"&nbsp;")))),"1"==KEDITORTOP.G_CURRKEDITOR._config.replaceSpace&&c&&(b=new RegExp(unescape("%20%20"),"g"),f=f.replace(b,"&nbsp; ")),d.chars(f)))}if(a==n)throw"Parse Error: "+a;n=a}e()};RAONK_EDITOR.HTMLParser.HTMLtoXML=function(a,c){var d="",g=KEDITORTOP.G_CURRKEDITOR._config.skipTagInParser;if(""!=g&&0==x){n=
n.replace(/,/g,",,");n=","+n+",";for(var g=g.split(","),e=g.length,b=0;b<e;b++)n=n.replace(","+g[b]+",","");n=n.replace(/,,/g,",");n=n.replace(/^,/g,"");n=n.replace(/,$/g,"");q=k(n);x=!0}RAONK_EDITOR.HTMLParser(a,c,{start:function(a,b,c){d+="<"+a;for(a=0;a<b.length;a++)d="href"==b[a].name||"src"==b[a].name?d+(" "+b[a].name+"="+b[a].quotationmark+b[a].value+b[a].quotationmark):""!=b[a].quotationmark?d+(" "+b[a].name+"="+b[a].quotationmark+b[a].value+b[a].quotationmark):d+(" "+b[a].name+'="'+b[a].escaped+
'"');d+=(c?"/":"")+">"},end:function(a){A[a]||(d+="</"+a+">")},chars:function(a){d+=a},comment:function(a){d="0"==KEDITORTOP.G_CURRKEDITOR._config.removeComment?d+("\x3c!--"+a+"--\x3e"):d+""}});return d};RAONK_EDITOR.HTMLParser.RemoveOfficeTag=function(a,c){if(""==a||void 0==a)return"";a=RAONK_EDITOR.HTMLParser.RemoveOfficeTag2(a);a=KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp(a);c&&(a=a.replace(/>\s+</g,"><"));return a};RAONK_EDITOR.HTMLParser.RemoveOfficeTag2=function(a){var c=RegExp("<o:p></o:p>",
"gi");a=a.replace(c,"");c=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<w:sdt[^>]*>","gi");a=a.replace(c,"");c=RegExp("</w:sdt>","gi");a=a.replace(c,"");if("1"==KEDITORTOP.G_CURRKEDITOR._config.removeLangAttribute&&(c=RegExp('<[^>]+(lang=["]?en-us["])[^>]*>',"gi"),c=a.match(c)))for(var d=c.length,g=0;g<d;g++){var e=c[g],b=RegExp('\\slang=[\\"]?en-us[\\"]?',"gi"),e=e.replace(b,
"");a=a.replace(c[g],e)}c=RegExp("<[^>]+(mso)[^>]*>","gi");if(c=a.match(c))for(d=c.length,g=0;g<d;g++)e=c[g],"1"==KEDITORTOP.G_CURRKEDITOR._config.removeMsoClass&&(b=RegExp('\\sclass=[\\"]?(mso)\\w+[\\"]?',"gi"),e=e.replace(b,"")),e=e.replace(/&quot;/gi,"^"),b=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;',"gi"),e=e.replace(b,""),b=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi"),e=e.replace(b,""),b=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"\\^@%\\.\\\\_]+; ?","gi"),e=e.replace(b,
""),b=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi"),e=e.replace(b,"$1"),e=e.replace(/\^/gi,"&quot;"),a=a.replace(c[g],e);c=RegExp("<v:shapetype ([^>]+)>[\\s\\S]*?</v:shapetype>","gi");a=a.replace(c,"");c=RegExp("<v:shape [^>]+>[\\s\\S]*?(<img [^>]+>)*?</v:shape>","gi");a=a.replace(c,"$1");c=RegExp("<v:shape ([^>]+)>[\\s\\S]*?</v:shape>","gi");a=a.replace(c,"");return a=a.replace(/<\!\[if ppt\]>/gi,"")};RAONK_EDITOR.HTMLParser.CheckNeedNestedHTML=function(a,c,d){var g=!1;"undefined"!=typeof c&&
""!=c&&(r=c);c=[];var e="p";"undefined"!=typeof d&&""!=d&&(e=d);d=e.split(",");var b=d.length;if(1<b)for(e=0;e<b;e++){var f=a.getElementsByTagName(d[e]);try{c=c.concat(Array.prototype.slice.call(f,0))}catch(h){for(var k=f.length,l=0;l<k;l++)c.push(f[l])}}else c=a.getElementsByTagName(e);e=0;for(a=c.length;e<a;e++)if(RAONK_EDITOR.HTMLParser.GetChildrenCount(c[e],!0)>r){g=!0;break}return g};RAONK_EDITOR.HTMLParser.GetChildrenCount=function(a,c){var d=0;a.childNodes&&(d=RAONK_EDITOR.HTMLParser.getChildrenCountForNestedHTML(a,
c)-a.childNodes.length);return d};RAONK_EDITOR.HTMLParser.getChildrenCountForNestedHTML=function(a,c){for(var d=0,g=a.childNodes.length,e=0;e<g;e++)1==a.childNodes[e].nodeType&&-1<",p,span,div,strong,b,".indexOf(","+a.childNodes[e].tagName.toLowerCase()+",")&&(c&&(d+=RAONK_EDITOR.HTMLParser.getChildrenCountForNestedHTML(a.childNodes[e],c)),d++);return d};RAONK_EDITOR.HTMLParser.CleanNestedHtml=function(a,c,d,g,e){function b(a){for(var b="",d=Array(a.childNodes.length),c=0;c<d.length;c++){d[c]=[];
d[c].push(a.childNodes[c]);f(a.childNodes[c],d[c]);var e=c,g=d[c],h=[],l=0;a:for(;l<g.length;l++){for(var k=0;k<h.length;k++)if(h[k]==g[l])continue a;h[h.length]=g[l]}d[e]=h;b+=d[c].join("")}return b}function f(a,b){for(var d=a.childNodes,c=0;c<d.length;c++)b.push(d[c]),d[c].hasChildNodes()&&1==d[c].nodeType&&"table"!=d[c].nodeName.toLowerCase()&&f(d[c],b);for(var d=0,e;d<b.length;d++){c=b[d];if(1==c.nodeType)if("table"==c.nodeName.toLowerCase())c=c.outerHTML;else{e=c.nodeName;if(-1==(" "+l.join(" ").toUpperCase()+
" ").search(" "+e.toUpperCase()+" ")){b.splice(d,1);d--;continue}e=c;for(var g="",k=0,m=void 0;k<e.attributes.length;k++)m=e.attributes[k],1==m.specified&&("style"==m.name?(m=h(e),""!=m&&(g+=' style="'+h(e)+'"')):""!=m.value&&(g+=" "+m.name+'="'+m.value+'"'));e=g;c="<"+c.nodeName.toLowerCase()+e+">"}else 3==c.nodeType&&(c=c.nodeValue.replace(/\n/g,""),c=c.replace(/(\s)\s+/g,"$1"),c=c.replace(/</g,"&lt;"),c=c.replace(/>/g,"&gt;"));b[d]=c}return b}function h(a){for(var b="",c=0,d=k.length,e;c<d;c++)a.currentStyle?
e=a.currentStyle[k[c]]:window.getComputedStyle&&(e=document.defaultView.getComputedStyle(a,null).getPropertyValue(k[c])),b+=k[c]+":"+e+";";return b}var k=[],l="p a abbr acronym applet b basefont bdo big br button cite code del dfn em font i iframe img input ins kbd label map object q s samp script select small strike strong sub sup textarea tt u var".split(" ");"undefined"!=typeof d&&""!=d&&(r=parseInt(d));d="p";"undefined"!=typeof g&&""!=g&&(d=g);g=a._DOC;"undefined"!=typeof e&&""!=e&&(g=e);var m=
[];e=d.split(",");var p=e.length;if(1<p)for(d=0;d<p;d++){var n=g.getElementsByTagName(e[d]);try{m=m.concat(Array.prototype.slice.call(n,0))}catch(t){for(var u=n.length,q=0;q<u;q++)m.push(n[q])}}else m=g.getElementsByTagName(d);e=!1;d=0;for(p=m.length;d<p;d++)if(RAONK_EDITOR.HTMLParser.GetChildrenCount(m[d],!0)>r){e=!0;break}if(e)if(g&&g!=a._DOC)try{d=0;for(var p=m.length,v;d<p;d++)RAONK_EDITOR.HTMLParser.GetChildrenCount(m[d],!0)>r&&(v=b(m[d]),v=RAONK_EDITOR.HTMLParser.HTMLtoXML(v),m[d].innerHTML=
v);return g.innerHTML}catch(w){}else showProcessingBackground(),setTimeout(function(){a._BODY.contentEditable=!1;try{if("2"==c)KEDITORTOP.RAONKEDITOR.Commands("select_all",a.ID),KEDITORTOP.RAONKEDITOR.Commands("remove_css",a.ID),KEDITORTOP.RAONKEDITOR.Commands("remove_format",a.ID),a._FRAMEWIN.setFocusToBody(),setTimeout(function(){a._FRAMEWIN.doSetCaretPosition(a._BODY.firstChild,0)},20);else for(var d=0,e=m.length,f;d<e;d++)RAONK_EDITOR.HTMLParser.GetChildrenCount(m[d],!0)>r&&(f=b(m[d]),f=RAONK_EDITOR.HTMLParser.HTMLtoXML(f),
m[d].innerHTML=f)}catch(g){}hideProcessingBackground();a._BODY.contentEditable=!0},G_Progress_LoadTime)};RAONK_EDITOR.HTMLParser.makeMap=function(a){return k(a)}})();
